# Generated by Django 5.1 on 2024-08-08 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название уровня')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('min_balance', models.IntegerField(verbose_name='Минимальный баланс для получения уровня')),
            ],
        ),
        migrations.CreateModel(
            name='Social_Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название социальной сети')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название задания')),
                ('url', models.CharField(max_length=1000, verbose_name='Ссылка')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.social_network', verbose_name='Соц. сеть')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('username', models.CharField(max_length=250, verbose_name='Username')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('energy', models.IntegerField(verbose_name='Энергия')),
                ('tap_count', models.IntegerField(verbose_name='Очки/Нажатие')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level', verbose_name='Уровень')),
            ],
        ),
    ]
