# Generated by Django 5.1 on 2024-08-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
        migrations.AlterModelOptions(
            name='social_network',
            options={'verbose_name': 'Соц. сеть', 'verbose_name_plural': 'Соц. сети'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='earn',
            field=models.IntegerField(default=0, verbose_name='Вознаграждение за задание'),
        ),
    ]
