# Generated by Django 5.1 on 2024-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_level_options_alter_social_network_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task_list',
            field=models.ManyToManyField(to='core.tasks', verbose_name='Список выполненных заданий'),
        ),
    ]
