# Generated by Django 5.1 on 2024-08-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referals',
            field=models.ManyToManyField(blank=True, null=True, to='core.user', verbose_name='Рефералы пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='energy',
            field=models.IntegerField(default=1000, verbose_name='Энергия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tap_count',
            field=models.IntegerField(default=1, verbose_name='Очки/Нажатие'),
        ),
        migrations.AlterField(
            model_name='user',
            name='task_list',
            field=models.ManyToManyField(blank=True, null=True, to='core.tasks', verbose_name='Список выполненных заданий'),
        ),
    ]
