# Generated by Django 5.1 on 2024-08-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_referals_alter_user_balance_alter_user_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_referal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Реферал'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_per_hour',
            field=models.IntegerField(default=0, verbose_name='Заработок за секунду'),
        ),
    ]
