# Generated by Django 5.1 on 2024-09-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_referal_user_total_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_level', models.IntegerField(default=1, verbose_name='Уровень энергии')),
                ('price', models.IntegerField(default=1, verbose_name='Цена за повышение уровня')),
            ],
            options={
                'verbose_name': 'Уровень энергии',
                'verbose_name_plural': 'Уровни энергии',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='energy_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.energylevel', verbose_name='Уровень энергии'),
        ),
    ]
