# Generated by Django 5.1 on 2024-09-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_energylevel_user_energy_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap_level', models.IntegerField(default=1, verbose_name='Уровень нажатия')),
                ('price', models.IntegerField(default=1, verbose_name='Цена за повышение уровня')),
            ],
            options={
                'verbose_name': 'Уровень нажатия',
                'verbose_name_plural': 'Уровни нажатия',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tap_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.taplevel', verbose_name='Уровень нажатия'),
        ),
    ]
