# Generated by Django 5.1 on 2024-09-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_taplevel_user_tap_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название карточки')),
                ('img', models.ImageField(upload_to='media/', verbose_name='Изображение карточки')),
                ('price', models.IntegerField(verbose_name='Прайс за карточку')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
