# Generated by Django 5.0.2 on 2024-09-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="max_balance",
            field=models.IntegerField(
                default="0", verbose_name="Максимальный баланс для уровня"
            ),
            preserve_default=False,
        ),
    ]
