# Generated by Django 5.0.7 on 2024-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_level_max_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='earn_per_hour',
            field=models.IntegerField(default='1', verbose_name='Прибыль в час'),
            preserve_default=False,
        ),
    ]
