# Generated by Django 5.0.7 on 2024-09-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_card_earn_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='first_gradient',
            field=models.CharField(default='#', max_length=250, verbose_name='Верхний градиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='second_gradient',
            field=models.CharField(default='#', max_length=250, verbose_name='Нижний градиент'),
            preserve_default=False,
        ),
    ]
