# Generated by Django 5.0.7 on 2024-09-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_card_first_gradient_card_second_gradient'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'PR agency'), ('2', 'Products'), ('3', 'Geography')], max_length=250, null=True, verbose_name='Категория'),
        ),
    ]
