# Generated by Django 5.0.2 on 2024-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_card_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("1", "Marketing"), ("2", "System"), ("3", "Geography")],
                max_length=250,
                null=True,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="img",
            field=models.ImageField(upload_to="", verbose_name="Изображение карточки"),
        ),
    ]
